/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mplayer4anime_mpv_MpvSlave */

#ifndef _Included_mplayer4anime_mpv_MpvSlave
#define _Included_mplayer4anime_mpv_MpvSlave
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mplayer4anime_mpv_MpvSlave
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mplayer4anime_mpv_MpvSlave_play
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
